export { createCatalogRouter, type CatalogRouteHandlers } from './interfaces/api/routes.js';
export { RegisterServiceHandler } from './application/commands/register-service.js';
export { UpdateServiceOwnershipHandler } from './application/commands/update-service-ownership.js';
export { DeregisterServiceHandler } from './application/commands/deregister-service.js';
export { GetServiceHandler } from './application/queries/get-service.js';
export { SearchServicesHandler } from './application/queries/search-services.js';
export { GetDependencyGraphHandler, GetDependentsHandler } from './application/queries/get-dependency-graph.js';
export { GetTeamHandler, ListTeamsHandler } from './application/queries/get-team.js';
export { ReconciliationService } from './application/services/reconciliation-service.js';
export { DynamoDBServiceRepository } from './infrastructure/dynamodb/service-repository.js';
export { DynamoDBTeamRepository } from './infrastructure/dynamodb/team-repository.js';
export { DynamoDBDependencyRepository } from './infrastructure/dynamodb/dependency-repository.js';
export { GitHubOrgCrawler } from './infrastructure/github/github-crawler.js';
export { MonorepoDetector } from './infrastructure/github/monorepo-detector.js';
export { ResolveAwsMappingHandler } from './application/commands/resolve-aws-mapping.js';
export { AWSResourceScanner } from './infrastructure/aws/aws-scanner.js';
export type { Service } from './domain/entities/service.js';
export type { Team } from './domain/entities/team.js';
export type { Dependency } from './domain/entities/dependency.js';
